ParallelAssignment:
  Enabled: false

LineLength:
  Enabled: false

FileName:
  Enabled: false

CommandLiteral:
  Enabled: false

MethodLength:
  Enabled: false

AbcSize:
  Enabled: false

AsciiComments:
  Enabled: false

Documentation:
  Enabled: false

BlockDelimiters:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

PerceivedComplexity:
  Enabled: false

ClassLength:
  Enabled: false
