LineLength:
  Enabled: false

FileName:
  Enabled: false

CommandLiteral:
  Enabled: false

MethodLength:
  Enabled: false

AbcSize:
  Enabled: false

AsciiComments:
  Enabled: false

BlockDelimiters:
	Exclude:
		- '/spec/**/*'
